name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build-mex:
    runs-on: [ubuntu-20.04,windows-2019,macos-12,macos-14]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Remove old MEX files
      shell: bash
      run: rm -rf Solver/Mexfun/*
    - name: Build MEX files
      uses: matlab-actions/run-command@v2
      with:
        command: install_sdpt3 -rebuild
