name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build-mex:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Remove old MEX files
      shell: bash
      run: rm Solver/Mexfun/*.mex* Solver/Mexfun/*/*.mex*
    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Build MEX files
      uses: matlab-actions/run-command@v2
      with:
        command: install_sdpt3 -rebuild
